-- ============================================================================
-- BLOQUE 8: ESQUEMA MAESTRO UNIFICADO BELPA WEB (SUPABASE CLOUD + AUTH + PEDIDOS)
-- ============================================================================
-- BELPA CMS — BLOQUE 7: PEDIDOS REALES, CHECKOUT, GESTIÓN COMERCIAL Y TRAZABILIDAD
-- ============================================================================
-- Proyecto: BELPA WEB (BelpaBeauty & BelFlora)
-- Este archivo es 100% IDEMPOTENTE: puede ejecutarse múltiples veces sin error.
-- ============================================================================

-- 1. TABLA DE USUARIOS ADMINISTRADORES (AUTH RBAC)
CREATE TABLE IF NOT EXISTS public.admin_users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL DEFAULT 'admin' CHECK (role IN ('admin', 'editor')),
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admin view own profile" ON public.admin_users;
CREATE POLICY "Admin view own profile"
    ON public.admin_users
    FOR SELECT
    TO authenticated
    USING (id = auth.uid());

-- 2. FUNCIÓN DE SEGURIDAD is_admin() (SECURITY DEFINER SIN RECURSIÓN)
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
    SELECT EXISTS (
        SELECT 1 
        FROM public.admin_users 
        WHERE id = auth.uid() 
          AND role = 'admin' 
          AND is_active = true
    );
$$;

-- 3. TABLA DE PRODUCTOS (CATÁLOGO MAESTRO DE PRODUCCIÓN)
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    brand TEXT NOT NULL CHECK (brand IN ('flora', 'beauty')),
    category TEXT NOT NULL,
    filter_category TEXT NOT NULL DEFAULT 'rosas_ramos',
    price TEXT NOT NULL,
    raw_price NUMERIC NOT NULL CHECK (raw_price >= 0),
    original_price NUMERIC DEFAULT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    badge TEXT DEFAULT '',
    description TEXT DEFAULT '',
    media_id TEXT DEFAULT '',
    images TEXT[] NOT NULL DEFAULT '{}',
    is_active BOOLEAN NOT NULL DEFAULT true,
    is_featured BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Migraciones seguras si la tabla ya existía
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='original_price') THEN
        ALTER TABLE public.products ADD COLUMN original_price NUMERIC DEFAULT NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='sort_order') THEN
        ALTER TABLE public.products ADD COLUMN sort_order INTEGER NOT NULL DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='media_id') THEN
        ALTER TABLE public.products ADD COLUMN media_id TEXT DEFAULT '';
    END IF;
END $$;

-- Índices de alto rendimiento para consultas
CREATE INDEX IF NOT EXISTS idx_products_brand_active ON public.products(brand, is_active);
CREATE INDEX IF NOT EXISTS idx_products_filter_category ON public.products(filter_category);
CREATE INDEX IF NOT EXISTS idx_products_is_active ON public.products(is_active);
CREATE INDEX IF NOT EXISTS idx_products_is_featured ON public.products(is_featured);
CREATE INDEX IF NOT EXISTS idx_products_sort_order ON public.products(sort_order);

-- Trigger para updated_at automático
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_products_updated_at ON public.products;
CREATE TRIGGER set_products_updated_at
    BEFORE UPDATE ON public.products
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- 4. POLÍTICAS ROW LEVEL SECURITY (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read active products" ON public.products;
CREATE POLICY "Public read active products"
    ON public.products
    FOR SELECT
    TO anon, authenticated
    USING (is_active = true);

DROP POLICY IF EXISTS "Admin read all products" ON public.products;
CREATE POLICY "Admin read all products"
    ON public.products
    FOR SELECT
    TO authenticated
    USING (public.is_admin() = true);

DROP POLICY IF EXISTS "Admin insert products" ON public.products;
CREATE POLICY "Admin insert products"
    ON public.products
    FOR INSERT
    TO authenticated
    WITH CHECK (public.is_admin() = true);

DROP POLICY IF EXISTS "Admin update products" ON public.products;
CREATE POLICY "Admin update products"
    ON public.products
    FOR UPDATE
    TO authenticated
    USING (public.is_admin() = true)
    WITH CHECK (public.is_admin() = true);

DROP POLICY IF EXISTS "Admin delete products" ON public.products;
CREATE POLICY "Admin delete products"
    ON public.products
    FOR DELETE
    TO authenticated
    USING (public.is_admin() = true);

-- 5. BUCKET DE ALMACENAMIENTO (SUPABASE STORAGE)
INSERT INTO storage.buckets (id, name, public)
VALUES ('product-images', 'product-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "Public Read Product Images" ON storage.objects;
CREATE POLICY "Public Read Product Images"
    ON storage.objects
    FOR SELECT
    TO anon, authenticated
    USING (bucket_id = 'product-images');

DROP POLICY IF EXISTS "Admin Upload Product Images" ON storage.objects;
CREATE POLICY "Admin Upload Product Images"
    ON storage.objects
    FOR INSERT
    TO authenticated
    WITH CHECK (bucket_id = 'product-images' AND public.is_admin() = true);

DROP POLICY IF EXISTS "Admin Update Product Images" ON storage.objects;
CREATE POLICY "Admin Update Product Images"
    ON storage.objects
    FOR UPDATE
    TO authenticated
    USING (bucket_id = 'product-images' AND public.is_admin() = true);

DROP POLICY IF EXISTS "Admin Delete Product Images" ON storage.objects;
CREATE POLICY "Admin Delete Product Images"
    ON storage.objects
    FOR DELETE
    TO authenticated
    USING (bucket_id = 'product-images' AND public.is_admin() = true);

-- 6. MIGRACIÓN IDEMPOTENTE DE LOS 79 PRODUCTOS ORIGINALES
INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (1, 'Ramo Rapunzel Ref 001', 'flora', 'TEMÁTICAS & DISNEY', 'tematicas', '$80,000 COP', 80000, NULL, 0, 'Princesas 👑', 'Ramo temático de Rapunzel en limpiapipas artesanales de alta calidad. Incluye: 4 Lirios, 2 Gerberas, 2 Margaritas, 1 Tulipán, 1 Flor gota de sol, 1 Rosa, camaleón Pascal en limpiapipa, follaje y luces LED decorativas.', 'MAHQOp8EUfM', ARRAY['assets/optimized/catalog/item_1_MAHQOp8EUfM.webp']::text[], true, true)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (2, 'Ramo Rapunzel Ref 002', 'flora', 'TEMÁTICAS & DISNEY', 'tematicas', '$115,000 COP', 115000, NULL, 0, 'Princesas 👑', 'Ramo premium de Rapunzel tejido a mano. Incluye: 1 Lirio, 3 Gerberas, 2 Jazmín, 6 Tulipanes, 1 Flor gota de sol, 1 figura de Pascal artesanal, follaje y luces LED.', 'MAHShGd7zIc', ARRAY['assets/optimized/catalog/item_2_MAHShGd7zIc.webp']::text[], true, true)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (3, 'Ramo Cenicienta', 'flora', 'TEMÁTICAS & DISNEY', 'tematicas', '$80,000 COP', 80000, NULL, 0, 'Princesas 👑', 'Ramo mágico de Cenicienta con tonos celestes y blancos. Incluye flores artesanales, detalles temáticos de princesa, follaje decorativo y luces LED.', 'MAHRoxdMUYc', ARRAY['assets/optimized/catalog/item_3_MAHRoxdMUYc.webp']::text[], true, true)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (4, 'Ramo La Princesa y el Sapo', 'flora', 'TEMÁTICAS & DISNEY', 'tematicas', '$115,000 COP', 115000, NULL, 0, 'Princesas 👑', 'Inspirado en Tiana y el pantano mágico. Incluye: 1 Flor de loto, 1 Gerbera, 1 Tulipán, 2 Lirios, 2 ramas de follaje, figura de la luciérnaga Ray en limpiapipas y luces LED.', 'MAHRowNcbB8', ARRAY['assets/optimized/catalog/item_4_MAHRowNcbB8.webp']::text[], true, true)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (5, 'Ramo Lotso Deluxe (7 Tulipanes & Lirios)', 'flora', 'RAMOS CON PELUCHES', 'peluches', '$135,000 COP', 135000, NULL, 0, 'Peluches 🧸', 'Hermoso bouquet con peluche Lotso, 7 Tulipanes, 3 Lirios, 1 Lirio especial, 5 ramas de follaje y envoltura de lujo.', 'MAHQ4CuIp3g', ARRAY['assets/optimized/catalog/item_5_MAHQ4CuIp3g.webp']::text[], true, true)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (6, 'Ramo Lotso Rosas & Gerberas', 'flora', 'RAMOS CON PELUCHES', 'peluches', '$110,000 COP', 110000, NULL, 0, 'Peluches 🧸', 'Bouquet dulce de 7 Tulipanes, 2 Rosas, 3 Gerberas, follaje y peluche de Lotso con aroma delicioso.', 'MAHPmj2Tpbk', ARRAY['assets/optimized/catalog/item_6_MAHPmj2Tpbk.webp']::text[], true, true)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (7, 'Ramo Lotso Clásico (7 Tulipanes)', 'flora', 'RAMOS CON PELUCHES', 'peluches', '$80,000 COP', 80000, NULL, 0, 'Peluches 🧸', 'Ramo tierno con peluche de Lotso. Incluye: 7 Tulipanes, ramas de follaje y peluche suave de Lotso.', 'MAHS1Qb4eEc', ARRAY['assets/optimized/catalog/item_7_MAHS1Qb4eEc.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (8, 'Ramo Lotso Dormilón (Peluche 35 cm)', 'flora', 'RAMOS CON PELUCHES', 'peluches', '$135,000 COP', 135000, NULL, 0, 'Peluches 🧸', 'Ramo especial con peluche Lotso de 35 cm. Incluye: 6 Tulipanes, 3 Rosas, 1 Anémona, follaje y peluche grande de Lotso.', 'MAHS1RY-jEE', ARRAY['assets/optimized/catalog/item_8_MAHS1RY-jEE.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (9, 'Ramo Annita Rosado', 'flora', 'RAMOS CON PELUCHES', 'peluches', '$120,000 COP', 120000, NULL, 0, 'Peluches 🧸', 'Tierno ramo en tono Rosado con peluche. Incluye: 6 Tulipanes, 3 Lirios, 2 ramas de follaje y peluche afelpado.', 'MAHQudzb4eg', ARRAY['assets/optimized/catalog/item_9_MAHQudzb4eg.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (10, 'Ramo Anny 2.0 Rosado Pastel', 'flora', 'RAMOS CON PELUCHES', 'peluches', '$120,000 COP', 120000, NULL, 0, 'Peluches 🧸', 'Ramo en tonalidad Rosado Pastel. Incluye: 6 Tulipanes, 3 Lirios, 2 ramas de follaje y peluche delicado.', 'MAHQ4KYCeEQ', ARRAY['assets/optimized/catalog/item_10_MAHQ4KYCeEQ.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (11, 'Ramo Anny Ovejita Nude', 'flora', 'RAMOS CON PELUCHES', 'peluches', '$125,000 COP', 125000, NULL, 0, 'Peluches 🧸', 'Elegante bouquet en tono Rosado Nude. Incluye: 7 Tulipanes, 3 Lirios, 3 Rosas, follaje y peluche de ovejita ultra suave.', 'MAHPmncoNSc', ARRAY['assets/optimized/catalog/item_11_MAHPmncoNSc.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (12, 'Ramo My Melody', 'flora', 'RAMOS CON PELUCHES', 'peluches', '$70,000 COP', 70000, NULL, 0, 'Sanrio 🎀', 'Inspirado en My Melody. Incluye: 7 Tulipanes tejidos, follaje y peluche original de My Melody.', 'MAHQOsxcTQs', ARRAY['assets/optimized/catalog/item_12_MAHQOsxcTQs.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (13, 'Ramo Hello Kitty Ref 001', 'flora', 'RAMOS CON PELUCHES', 'peluches', '$125,000 COP', 125000, NULL, 0, 'Sanrio 🎀', 'Precioso ramo de Hello Kitty. Incluye: 5 Tulipanes, 3 Lirios, 3 Gerberas, 2 ramas de follaje y peluche de Hello Kitty.', 'MAHQaR4F-LI', ARRAY['assets/optimized/catalog/item_13_MAHQaR4F-LI.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (14, 'Ramo Hello Kitty Ref 002 (45 cm)', 'flora', 'RAMOS CON PELUCHES', 'peluches', '$150,000 COP', 150000, NULL, 0, 'Sanrio 🎀', 'Gran bouquet con peluche Hello Kitty gigante de 45 cm. Incluye: 10 Tulipanes, 4 Lirios, 1 Gerbera y follaje.', 'MAHS16mtKgM', ARRAY['assets/optimized/catalog/item_14_MAHS16mtKgM.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (15, 'Ramo Hello Kitty Ref 003 (6 Tulipanes)', 'flora', 'RAMOS CON PELUCHES', 'peluches', '$70,000 COP', 70000, NULL, 0, 'Sanrio 🎀', 'Bouquet tierno de 6 Tulipanes, 2 ramas de follaje y peluche Hello Kitty de 45 cm.', 'MAHRMue2NRs', ARRAY['assets/optimized/catalog/item_15_MAHRMue2NRs.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (16, 'Ramo Hello Kitty Ref 004 (50 cm)', 'flora', 'RAMOS CON PELUCHES', 'peluches', '$150,000 COP', 150000, NULL, 0, 'Sanrio 🎀', 'El regalo supremo para fans de Hello Kitty. Incluye: 5 Tulipanes, 4 Lirios, 2 Gerberas, Margarita mini, follaje y peluche Hello Kitty de 50 cm.', 'MAHRMuZHRJc', ARRAY['assets/optimized/catalog/item_16_MAHRMuZHRJc.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (17, 'Ramo Snoopy Ref 01', 'flora', 'RAMOS CON PELUCHES', 'peluches', '$78,000 COP', 78000, NULL, 0, 'Snoopy 🐶', 'Encantador ramo de 4 Tulipanes, 3 Gerberas, follaje y figura artesanal de Snoopy tejida en limpiapipas.', 'MAHRo4IM_QY', ARRAY['assets/optimized/catalog/item_17_MAHRo4IM_QY.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (18, 'Ramo Snoopy Ref 02 (12 Tulipanes)', 'flora', 'RAMOS CON PELUCHES', 'peluches', '$70,000 COP', 70000, NULL, 0, 'Snoopy 🐶', 'Arreglo primaveral de 12 Tulipanes artesanales, follaje y figura tejida de Snoopy en limpiapipas.', 'MAHST6bI3dM', ARRAY['assets/optimized/catalog/item_18_MAHST6bI3dM.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (19, 'Ramo Delirio (12 Lirios con Luces & Banda)', 'flora', 'LIRIOS', 'lirios', '$110,000 COP', 110000, NULL, 0, 'Lirios 🪷', 'Impactante ramo de 12 Lirios eternos hechos a mano, follaje, banda personalizada con frase y serie de luces LED.', 'MAHS1lNKdhw', ARRAY['assets/optimized/catalog/item_19_MAHS1lNKdhw.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (20, 'Ramo Belkis Lirios', 'flora', 'LIRIOS', 'lirios', '$90,000 COP', 90000, NULL, 0, 'Lirios 🪷', 'Ramo clásico y elegante con 12 Lirios eternos tejidos a mano y fino follaje decorativo.', 'MAHS14muKlY', ARRAY['assets/optimized/catalog/item_20_MAHS14muKlY.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (21, 'Ramo Gloria con Luces', 'flora', 'LIRIOS', 'lirios', '$50,000 COP', 50000, NULL, 0, 'Lirios 🪷', 'Delicado bouquet de 5 Lirios eternos artesanales, follaje y luces LED decorativas.', 'MAHS15WkPNM', ARRAY['assets/optimized/catalog/item_21_MAHS15WkPNM.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (22, 'Ramo Tuli (14 Tulipanes)', 'flora', 'TULIPANES', 'tulipanes', '$65,000 COP', 65000, NULL, 0, 'Tulipanes 🌷', 'Bouquet voluminoso y colorido de 14 Tulipanes tejidos a mano con limpiapipas de alta calidad y follaje.', 'MAHPmp3eA2I', ARRAY['assets/optimized/catalog/item_22_MAHPmp3eA2I.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (23, 'Ramo Belkis Tulipanes (15 Tulipanes)', 'flora', 'TULIPANES', 'tulipanes', '$55,000 COP', 55000, NULL, 0, 'Tulipanes 🌷', 'Ramillete dulce y duradero de 15 Tulipanes eternos en combinación de tonos pasteles.', 'MAHS15aJDEc', ARRAY['assets/optimized/catalog/item_23_MAHS15aJDEc.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (24, 'Ramo Mila (10 Tulipanes)', 'flora', 'TULIPANES', 'tulipanes', '$50,000 COP', 50000, NULL, 0, 'Tulipanes 🌷', 'Ramo coqueto de 10 Tulipanes eternos y ramas de follaje suave.', 'MAHS1_XlHvk', ARRAY['assets/optimized/catalog/item_24_MAHS1_XlHvk.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (25, 'Ramo Evelyn Tulipanes & Lirios', 'flora', 'TULIPANES', 'tulipanes', '$70,000 COP', 70000, NULL, 0, 'Tulipanes 🌷', 'Hermosa combinación de 7 Tulipanes, 3 Lirios, 6 copitos (flores mini) y follaje.', 'MAHQW71FD-c', ARRAY['assets/optimized/catalog/item_25_MAHQW71FD-c.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (26, 'Ramo Lolita (6 Tulisnoopy)', 'flora', 'TULIPANES', 'tulipanes', '$55,000 COP', 55000, NULL, 0, 'Tulipanes 🌷', 'Ramo con 6 Tulisnoopy (tulipanes combinados con carita de Snoopy) y follaje decorativo.', 'MAHS1hLOLCI', ARRAY['assets/optimized/catalog/item_26_MAHS1hLOLCI.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (27, 'Ramo Evelyn Mini Mix', 'flora', 'TULIPANES', 'tulipanes', '$46,000 COP', 46000, NULL, 0, 'Tulipanes 🌷', 'Ramo accesible y tierno con 3 Tulipanes, 2 Tulisnoopy, 1 Lirio y follaje.', 'MAHS1m_fq6s', ARRAY['assets/optimized/catalog/item_27_MAHS1m_fq6s.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (28, 'Ramo Majo (3 Girasoles & 3 Tulipanes)', 'flora', 'GIRASOLES', 'girasoles', '$65,000 COP', 65000, NULL, 0, 'Girasoles 🌻', 'Lleno de energía y luz. Incluye: 3 Girasoles grandes, 3 Tulipanes y ramas de follaje.', 'MAHRiZYz2-Q', ARRAY['assets/optimized/catalog/item_28_MAHRiZYz2-Q.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (29, 'Ramo Yari (2 Girasoles & 2 Tulipanes)', 'flora', 'GIRASOLES', 'girasoles', '$50,000 COP', 50000, NULL, 0, 'Girasoles 🌻', 'Detalle radiante de 2 Girasoles y 2 Tulipanes artesanales con follaje verde.', 'MAHS1jyP-yc', ARRAY['assets/optimized/catalog/item_29_MAHS1jyP-yc.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (30, 'Ramo Luz con Corona & Banda', 'flora', 'GIRASOLES', 'girasoles', '$92,000 COP', 92000, NULL, 0, 'Girasoles 🌻', 'Ramo regio de 6 Girasoles eternos, follaje, corona dorada decorativa y banda floral con frase personalizada.', 'MAHS1gXeVI0', ARRAY['assets/optimized/catalog/item_30_MAHS1gXeVI0.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (31, 'Ramo Sol (7 Girasoles Mini)', 'flora', 'GIRASOLES', 'girasoles', '$60,000 COP', 60000, NULL, 0, 'Girasoles 🌻', 'Ramo alegre compuesto por 7 Girasoles mini y follaje natural decorativo.', 'MAHS2HJml-s', ARRAY['assets/optimized/catalog/item_31_MAHS2HJml-s.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (32, 'Ramo Dariana (6 Gerberas & 6 Tulipanes)', 'flora', 'GERBERAS', 'gerberas', '$65,000 COP', 65000, NULL, 0, 'Gerberas 🌸', 'Colorido ramo que reúne 6 Gerberas y 6 Tulipanes tejidos a mano con follaje.', 'MAHS2IldEgw', ARRAY['assets/optimized/catalog/item_32_MAHS2IldEgw.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (33, 'Ramo Jasley (12 Gerberas)', 'flora', 'GERBERAS', 'gerberas', '$75,000 COP', 75000, NULL, 0, 'Gerberas 🌸', 'Abundante bouquet de 12 Gerberas eternas en paleta vibrante de colores y follaje.', 'MAHS2PRaE_E', ARRAY['assets/optimized/catalog/item_33_MAHS2PRaE_E.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (34, 'Ramo Yenni con Lavandas', 'flora', 'RAMOS PRIMAVERA', 'primavera', '$60,000 COP', 60000, NULL, 0, 'Primavera 💐', 'Delicada armonía de 6 Tulipanes, 3 Lirios, 2 ramitas de Lavanda aromática y follaje.', 'MAHS1mDKXcg', ARRAY['assets/optimized/catalog/item_34_MAHS1mDKXcg.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (35, 'Ramo Evelyn Gran Primavera', 'flora', 'RAMOS PRIMAVERA', 'primavera', '$115,000 COP', 115000, NULL, 0, 'Primavera 💐', 'El arreglo primaveral más completo: 7 Tulipanes, 3 Lirios, 2 Girasoles, 2 Gerberas, 2 Margaritas, 1 Anémona y follaje.', 'MAHS1vHW5rE', ARRAY['assets/optimized/catalog/item_35_MAHS1vHW5rE.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (36, 'Ramo Floral', 'flora', 'RAMOS PRIMAVERA', 'primavera', '$70,000 COP', 70000, NULL, 0, 'Primavera 💐', 'Hermosa combinación de 4 Tulipanes, 4 Lirios, 2 Margaritas, 2 Gerberas y ramas de follaje.', 'MAHPmkuxQdY', ARRAY['assets/optimized/catalog/item_36_MAHPmkuxQdY.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (37, 'Ramo Lili', 'flora', 'RAMOS PRIMAVERA', 'primavera', '$55,000 COP', 55000, NULL, 0, 'Primavera 💐', 'Ramo balanceado de 3 Tulipanes, 4 Lirios y follaje decorativo.', 'MAHS1hpx7Ks', ARRAY['assets/optimized/catalog/item_37_MAHS1hpx7Ks.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (38, 'Ramo Van Gogh', 'flora', 'RAMOS PRIMAVERA', 'primavera', '$75,000 COP', 75000, NULL, 0, 'Inspiración 🎨', 'Inspirado en la paleta de colores de Vincent Van Gogh. Incluye: 7 Tulipanes, 1 Girasol, 2 Gerberas y follaje.', 'MAHQOl9WAv4', ARRAY['assets/optimized/catalog/item_38_MAHQOl9WAv4.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (39, 'Ramo Moli', 'flora', 'RAMOS PRIMAVERA', 'primavera', '$75,000 COP', 75000, NULL, 0, 'Primavera 💐', 'Bouquet dulce y fresco con 7 Tulipanes, 2 Lirios y follaje.', 'MAHPmqpV1sY', ARRAY['assets/optimized/catalog/item_39_MAHPmqpV1sY.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (40, 'Ramo Tamy (8 Tulipanes & 8 Lirios)', 'flora', 'RAMOS PRIMAVERA', 'primavera', '$100,000 COP', 100000, NULL, 0, 'Primavera 💐', 'Gran bouquet de 8 Tulipanes y 8 Lirios eternos con envoltura de satín de lujo.', 'MAHNZFjOzxA', ARRAY['assets/optimized/catalog/item_40_MAHNZFjOzxA.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (41, 'Ramo Love (Rosas, Tulipanes & Girasol)', 'flora', 'RAMOS PRIMAVERA', 'primavera', '$70,000 COP', 70000, NULL, 0, 'Romance 💕', 'Ramo romántico de 5 Tulipanes, 1 Girasol, 5 Rosas eternas y follaje.', 'MAHNaRFaFjE', ARRAY['assets/optimized/catalog/item_41_MAHNaRFaFjE.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (42, 'Ramo Mía', 'flora', 'RAMOS PRIMAVERA', 'primavera', '$45,000 COP', 45000, NULL, 0, 'Primavera 💐', 'Mix primaveral: 1 Girasol, 1 Lirio, 1 Margarita, 1 Capullo, 1 Anémona, 2 Gerberas y follaje.', 'MAHIuBIvVmQ', ARRAY['assets/optimized/catalog/item_42_MAHIuBIvVmQ.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (43, 'Ramo Beth con Hortensia', 'flora', 'RAMOS PRIMAVERA', 'primavera', '$95,000 COP', 95000, NULL, 0, 'Primavera 💐', 'Arreglo exclusivo de 2 Lirios, 2 Gerberas, 2 Anémonas, 2 Rosas, 2 Tulipanes, 1 Hortensia y follaje.', 'MAHS2MZ2ubY', ARRAY['assets/optimized/catalog/item_43_MAHS2MZ2ubY.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (44, 'Ramo Ashley', 'flora', 'RAMOS PRIMAVERA', 'primavera', '$55,000 COP', 55000, NULL, 0, 'Primavera 💐', 'Ramillete dulce con 7 Tulipanes, 2 Gerberas, 1 Lirio y follaje.', 'MAHQaUTpCPQ', ARRAY['assets/optimized/catalog/item_44_MAHQaUTpCPQ.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (45, 'Ramo Thalía', 'flora', 'RAMOS PRIMAVERA', 'primavera', '$55,000 COP', 55000, NULL, 0, 'Primavera 💐', 'Incluye: 2 Lirios, 2 Gerberas, 1 Girasol, 1 Tulipán, 1 Capullo y follaje.', 'MAHQcrNeUCI', ARRAY['assets/optimized/catalog/item_45_MAHQcrNeUCI.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (46, 'Ramo Jess con Espejo', 'flora', 'FLORES CON ESPEJO', 'espejos', '$110,000 COP', 110000, NULL, 0, 'Con Espejo 🪞', 'Innovador arreglo sobre espejo decorativo. Incluye: 2 Lirios, 1 Margarita, 1 Gerbera, 2 Tulipanes, 1 Girasol mini, 1 Rosa, follaje y espejo incorporado.', 'MAHQcxF-Omg', ARRAY['assets/optimized/catalog/item_46_MAHQcxF-Omg.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (47, 'Ramo Juli con Espejo', 'flora', 'FLORES CON ESPEJO', 'espejos', '$105,000 COP', 105000, NULL, 0, 'Con Espejo 🪞', 'Diseño elegante con espejo: 2 Tulipanes, 1 Girasol mini, 1 Gerbera, 3 Lirios, 1 Margarita, follaje y espejo.', 'MAHQc4kU0J0', ARRAY['assets/optimized/catalog/item_47_MAHQc4kU0J0.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (48, 'Ramo Cecilia con Espejo', 'flora', 'FLORES CON ESPEJO', 'espejos', '$95,000 COP', 95000, NULL, 0, 'Con Espejo 🪞', 'Incluye: 3 Lirios, 1 Margarita, 2 Gerberas, 1 Tulipán, 1 Girasol, 1 Girasol mini, follaje y espejo.', 'MAHQcw8Hnw8', ARRAY['assets/optimized/catalog/item_48_MAHQcw8Hnw8.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (49, 'Ramo Romy (9 Gerberas con Espejo)', 'flora', 'FLORES CON ESPEJO', 'espejos', '$85,000 COP', 85000, NULL, 0, 'Con Espejo 🪞', 'Hermoso conjunto de 9 Gerberas eternas montadas con espejo decorativo y follaje.', 'MAHQcxvnl8s', ARRAY['assets/optimized/catalog/item_49_MAHQcxvnl8s.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (50, 'Cápsula Girasol Grande', 'flora', 'CÁPSULAS DE CRISTAL', 'capsulas', '$40,000 COP', 40000, NULL, 0, 'Cúpula Cristal 🔮', 'Cápsula de cristal fino con 1 Girasol artesanal grande en base de madera decorativa.', 'MAHQW-0A_E8', ARRAY['assets/optimized/catalog/item_50_MAHQW-0A_E8.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (51, 'Cápsula Girasol Mini', 'flora', 'CÁPSULAS DE CRISTAL', 'capsulas', '$16,000 COP', 16000, NULL, 0, 'Mini Cúpula 🔮', 'Cápsula compacta con 1 Girasol mini tejido a mano, ideal para escritorio o detalle sorpresa.', 'MAHQW_SOR_o', ARRAY['assets/optimized/catalog/item_51_MAHQW_SOR_o.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (52, 'Cápsula Girasol con Luces LED', 'flora', 'CÁPSULAS DE CRISTAL', 'capsulas', '$40,000 COP', 40000, NULL, 0, 'Con Luces ✨', 'Cápsula de cristal con Girasol grande, base y luces LED a pila que crean una atmósfera mágica de noche.', 'MAHQW9Qr7Yc', ARRAY['assets/optimized/catalog/item_52_MAHQW9Qr7Yc.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (53, 'Cápsula Rapunzel Flor Fulgor', 'flora', 'CÁPSULAS DE CRISTAL', 'capsulas', '$45,000 COP', 45000, NULL, 0, 'Princesas 👑', 'Inspirada en la Flor Dorada de Rapunzel. Incluye cúpula de cristal, flor fulgor tejida y luces LED a pila.', 'MAHQWx9ZlBE', ARRAY['assets/optimized/catalog/item_53_MAHQWx9ZlBE.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (54, 'Cápsula Love (Rosa Grande)', 'flora', 'CÁPSULAS DE CRISTAL', 'capsulas', '$35,000 COP', 35000, NULL, 0, 'Cúpula Cristal 🔮', 'Cápsula de cristal con 1 Rosa eterna grande de crochet artesanal.', 'MAHQW1udt2g', ARRAY['assets/optimized/catalog/item_54_MAHQW1udt2g.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (55, 'Cápsula Rouse Triple (3 Rosas)', 'flora', 'CÁPSULAS DE CRISTAL', 'capsulas', '$60,000 COP', 60000, NULL, 0, 'Cúpula Cristal 🔮', 'Cápsula de cristal con 3 Rosas eternas combinadas en tonos románticos.', 'MAHQWw6P6m4', ARRAY['assets/optimized/catalog/item_55_MAHQWw6P6m4.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (56, 'Cápsula Pink (Rosa Preservada)', 'flora', 'CÁPSULAS DE CRISTAL', 'capsulas', '$55,000 COP', 55000, NULL, 0, 'Preservadas 🌸', 'Cápsula de cristal de lujo con Rosa rosada grande preservada de larga duración.', 'MAHQWzuw9OQ', ARRAY['assets/optimized/catalog/item_56_MAHQWzuw9OQ.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (57, 'Cápsula Rosa Amarilla Preservada', 'flora', 'CÁPSULAS DE CRISTAL', 'capsulas', '$55,000 COP', 55000, NULL, 0, 'Preservadas 💛', 'Cápsula de cristal con Rosa amarilla grande preservada que simboliza alegría y luz eterna.', 'MAHQW6wxDo4', ARRAY['assets/optimized/catalog/item_57_MAHQW6wxDo4.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (58, 'Bouquet Ramo Enredados con Hello Kitty', 'flora', 'BOUQUETS', 'bouquets', '$85,000 COP', 85000, NULL, 0, 'Bouquet 🎀', 'Bouquet temático con 2 Lirios, 5 Tulipanes, follaje y peluche de Hello Kitty.', 'MAHPRzSttpY', ARRAY['assets/optimized/catalog/item_58_MAHPRzSttpY.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (59, 'Bouquet Ramo Ashley con Peluche', 'flora', 'BOUQUETS', 'bouquets', '$73,000 COP', 73000, NULL, 0, 'Bouquet 🎀', 'Bouquet primaveral con 3 Tulipanes, 1 Gerbera, 1 Rosa, 1 Anémona, follaje y peluche tierno.', 'MAHQbeC55WU', ARRAY['assets/optimized/catalog/item_59_MAHQbeC55WU.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (60, 'Cuadro Eterno Mía', 'flora', 'CUADROS ETERNOS', 'cuadros', '$44,000 COP', 44000, NULL, 0, 'Cuadros 🖼️', 'Cuadro decorativo 3D con flores eternas, luces LED integradas y frase personalizada a elección.', 'MAHQXPO_784', ARRAY['assets/optimized/catalog/item_60_MAHQXPO_784.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (61, 'Cuadro Eterno Sol', 'flora', 'CUADROS ETERNOS', 'cuadros', '$45,000 COP', 45000, NULL, 0, 'Cuadros 🖼️', 'Cuadro con composición de girasoles y flores amarillas, luces LED y dedicatoria personalizada.', 'MAHQXMNSJy0', ARRAY['assets/optimized/catalog/item_61_MAHQXMNSJy0.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (62, 'Cuadro Eterno Lía', 'flora', 'CUADROS ETERNOS', 'cuadros', '$50,000 COP', 50000, NULL, 0, 'Cuadros 🖼️', 'Hermoso cuadro de fondo pastel con ramo de flores de crochet en relieve, luces cálidas y dedicatoria.', 'MAHQXK9ApYM', ARRAY['assets/optimized/catalog/item_62_MAHQXK9ApYM.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (63, 'Cuadro Eterno Antonella', 'flora', 'CUADROS ETERNOS', 'cuadros', '$35,000 COP', 35000, NULL, 0, 'Cuadros 🖼️', 'Cuadro compacto de flores eternas con luces LED y mensaje personalizado para esa persona especial.', 'MAHQXBS9UAw', ARRAY['assets/optimized/catalog/item_63_MAHQXBS9UAw.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (64, 'Materito Carli', 'flora', 'MATERITOS & JARRONES', 'materitos', '$14,000 COP', 14000, NULL, 0, 'Materito 🪴', 'Materito artesanal con flor tejida en limpiapipas, perfecto para decoración de escritorio o repisa.', 'MAHQck5nZrI', ARRAY['assets/optimized/catalog/item_64_MAHQck5nZrI.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (65, 'Jarrón de Vidrio Blanca', 'flora', 'MATERITOS & JARRONES', 'materitos', '$95,000 COP', 95000, NULL, 0, 'Jarrón Lujo 🏺', 'Elegante jarrón de vidrio con arreglo floral completo de flores eternas tejidas a mano.', 'MAHQcoXs6oo', ARRAY['assets/optimized/catalog/item_65_MAHQcoXs6oo.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (66, 'Materito Belinda', 'flora', 'MATERITOS & JARRONES', 'materitos', '$15,000 COP', 15000, NULL, 0, 'Materito 🪴', 'Materito decorativo con flor de crochet en maceta miniatura.', 'MAHQcku9IYs', ARRAY['assets/optimized/catalog/item_66_MAHQcku9IYs.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (67, 'Materito Roxi', 'flora', 'MATERITOS & JARRONES', 'materitos', '$18,000 COP', 18000, NULL, 0, 'Materito 🪴', 'Materito artesanal con diseño floral especial en maceta de color pastel.', 'MAHQcmSBWVg', ARRAY['assets/optimized/catalog/item_67_MAHQcmSBWVg.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (68, 'Figurita Vaquita Lola', 'flora', 'FIGURITAS', 'figuritas', '$40,000 COP', 40000, NULL, 0, 'Figuritas ✨', 'Figura coleccionable de la Vaquita Lola modelada artesanalmente con limpiapipas de alta suavidad.', 'MAHQcwpIBq8', ARRAY['assets/optimized/catalog/item_68_MAHQcwpIBq8.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (69, 'Figurita Pingüi', 'flora', 'FIGURITAS', 'figuritas', '$30,000 COP', 30000, NULL, 0, 'Figuritas ✨', 'Adorable pingüinito artesanal hecho 100% a mano con limpiapipas.', 'MAHQrZJuXQU', ARRAY['assets/optimized/catalog/item_69_MAHQrZJuXQU.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (70, 'Figurita Snoopy', 'flora', 'FIGURITAS', 'figuritas', '$40,000 COP', 40000, NULL, 0, 'Snoopy 🐶', 'Figura 3D de Snoopy en limpiapipas, con detalles tiernos y base decorativa.', 'MAHQrYgr7ZY', ARRAY['assets/optimized/catalog/item_70_MAHQrYgr7ZY.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (71, 'Figurita Hombre Araña (Spider-Man)', 'flora', 'FIGURITAS', 'figuritas', '$25,000 COP', 25000, NULL, 0, 'Marvel 🕷️', 'Figura flexible y detallada de Spider-Man hecha a mano con limpiapipas rojo y azul.', 'MAHRNDSL_Lc', ARRAY['assets/optimized/catalog/item_71_MAHRNDSL_Lc.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (72, 'Figurita Virgen de Guadalupe', 'flora', 'FIGURITAS', 'figuritas', '$40,000 COP', 40000, NULL, 0, 'Especial 🕊️', 'Hermosa representación artesanal de la Virgen de Guadalupe con manto estrellado y aureola dorada.', 'MAHST6fgGYw', ARRAY['assets/optimized/catalog/item_72_MAHST6fgGYw.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (73, 'Figurita Rapunzel', 'flora', 'FIGURITAS', 'figuritas', '$45,000 COP', 45000, NULL, 0, 'Princesas 👑', 'Figura de Rapunzel con su largo cabello dorado trenzado con florecitas y vestido lila.', 'MAHS2PEK93E', ARRAY['assets/optimized/catalog/item_73_MAHS2PEK93E.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (74, 'Llavero Gerbera Artesanal', 'flora', 'LLAVEROS', 'llaveros', '$15,000 COP', 15000, NULL, 0, 'Llaveros 🔑', 'Lindo llavero con gerbera tejida a mano y herraje resistente para tus llaves, bolso o morral.', 'MAHS2NuSbvY', ARRAY['assets/optimized/catalog/item_74_MAHS2NuSbvY.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (75, 'Kit de Skincare Rutina Completa', 'beauty', 'CUIDADO FACIAL', 'skincare', '$38,000 COP', 38000, NULL, 0, 'Viral 🔥', 'El set definitivo para el cuidado facial diario. Incluye gel limpiador suave, tónico equilibrante y crema hidratante iluminadora para dejar la piel fresca, suave y protegida.', '', ARRAY['assets/optimized/product_2.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (76, 'Combo Moño Satín & Lip Gloss Trend', 'beauty', 'ACCESORIOS Y LABIOS', 'accesorios', '$22,000 COP', 22000, NULL, 0, 'Nuevo 🎀', 'El kit ideal de moños elegantes estilo satín combinados con brillo labial ultra hidratante. Perfecto para añadir un toque tierno a tu look diario.', '', ARRAY['assets/optimized/product_3.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (77, 'Sheglam Lip Gloss Sparkling', 'beauty', 'MAQUILLAJE LABIOS', 'maquillaje', '$18,000 COP', 18000, NULL, 0, 'Best Seller ⭐', 'Brillo labial viral con micro-destellos de purpurina que reflejan la luz de manera espectacular. Proporciona hidratación profunda y volumen óptico sin sensación pegajosa.', '', ARRAY['assets/optimized/product_4.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (78, 'Pestañina Prosa 4 en 1 Waterproof', 'beauty', 'MAQUILLAJE OJOS', 'maquillaje', '$12,000 COP', 12000, NULL, 0, 'Básico 👀', 'Fórmula profesional de larga duración resistente al agua. Enriquecida con aceites naturales de hueso de mamey, sábila, jojoba y germen de trigo.', '', ARRAY['assets/optimized/product_5.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

INSERT INTO public.products (id, name, brand, category, filter_category, price, raw_price, original_price, sort_order, badge, description, media_id, images, is_active, is_featured)
VALUES (79, 'Alissha Jelly Blush Tinta Rubor', 'beauty', 'MAQUILLAJE MEJILLAS', 'maquillaje', '$15,000 COP', 15000, NULL, 0, 'Nuevo Rubor 🍮', 'Divertido rubor y tinta multiusos con una textura jelly gelatinosa única. Es sumamente fácil de difuminar, refresca tu piel y aporta una tinta de larga duración.', '', ARRAY['assets/optimized/product_6.webp']::text[], true, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    category = EXCLUDED.category,
    filter_category = EXCLUDED.filter_category,
    price = EXCLUDED.price,
    raw_price = EXCLUDED.raw_price,
    badge = EXCLUDED.badge,
    description = EXCLUDED.description,
    media_id = EXCLUDED.media_id,
    images = EXCLUDED.images;

-- Sincronizar secuencia de IDs
SELECT setval(pg_get_serial_sequence('public.products', 'id'), COALESCE((SELECT MAX(id) FROM public.products), 1));


-- ============================================================================

-- Función auxiliar para generación atómica de números de pedido en servidor
CREATE SEQUENCE IF NOT EXISTS public.order_number_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE FUNCTION public.get_next_order_number()
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    next_val BIGINT;
    year_str TEXT;
BEGIN
    next_val := nextval('public.order_number_seq');
    year_str := to_char(CURRENT_DATE, 'YYYY');
    RETURN 'BELPA-' || year_str || '-' || lpad(next_val::text, 6, '0');
END;
$$;

-- 7. TABLAS DE GESTIÓN COMERCIAL, PEDIDOS Y TRAZABILIDAD (BLOQUE 7)
-- ============================================================================

-- Tabla Principal de Pedidos
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number TEXT NOT NULL UNIQUE,
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    customer_email TEXT DEFAULT '',
    delivery_method TEXT NOT NULL,
    delivery_date DATE,
    delivery_address TEXT DEFAULT '',
    client_notes TEXT DEFAULT '',
    subtotal NUMERIC NOT NULL CHECK (subtotal >= 0),
    delivery_cost NUMERIC NOT NULL DEFAULT 0 CHECK (delivery_cost >= 0),
    discount NUMERIC NOT NULL DEFAULT 0 CHECK (discount >= 0),
    total NUMERIC NOT NULL CHECK (total >= 0),
    currency TEXT NOT NULL DEFAULT 'COP',
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'preparing', 'ready', 'out_for_delivery', 'delivered', 'cancelled')),
    payment_status TEXT NOT NULL DEFAULT 'pending' CHECK (payment_status IN ('pending', 'paid', 'partial', 'refunded')),
    source TEXT NOT NULL DEFAULT 'website' CHECK (source IN ('website', 'whatsapp', 'admin', 'other')),
    whatsapp_message TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Trigger para updated_at en orders
DROP TRIGGER IF EXISTS set_orders_updated_at ON public.orders;
CREATE TRIGGER set_orders_updated_at
    BEFORE UPDATE ON public.orders
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Tabla de Items / Fotografía Histórica del Pedido
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    product_name TEXT NOT NULL,
    product_brand TEXT NOT NULL,
    unit_price NUMERIC NOT NULL CHECK (unit_price >= 0),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    line_total NUMERIC NOT NULL CHECK (line_total >= 0),
    product_image TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Tabla de Historial y Auditoría de Estados del Pedido
CREATE TABLE IF NOT EXISTS public.order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    old_status TEXT,
    new_status TEXT NOT NULL,
    changed_by TEXT NOT NULL DEFAULT 'admin',
    note TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Índices de Alto Rendimiento para Búsqueda y Filtros
CREATE INDEX IF NOT EXISTS idx_orders_order_number ON public.orders(order_number);
CREATE INDEX IF NOT EXISTS idx_orders_customer_phone ON public.orders(customer_phone);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_payment_status ON public.orders(payment_status);
CREATE INDEX IF NOT EXISTS idx_orders_delivery_date ON public.orders(delivery_date);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders(created_at);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON public.order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_status_history_order_id ON public.order_status_history(order_id);

-- Habilitar RLS en Tablas de Pedidos
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_status_history ENABLE ROW LEVEL SECURITY;

-- Políticas RLS para Orders
DROP POLICY IF EXISTS "Public insert orders" ON public.orders;
CREATE POLICY "Public insert orders"
    ON public.orders
    FOR INSERT
    TO anon, authenticated
    WITH CHECK (true);

DROP POLICY IF EXISTS "Admin view orders" ON public.orders;
CREATE POLICY "Admin view orders"
    ON public.orders
    FOR SELECT
    TO authenticated
    USING (public.is_admin() = true);

DROP POLICY IF EXISTS "Admin update orders" ON public.orders;
CREATE POLICY "Admin update orders"
    ON public.orders
    FOR UPDATE
    TO authenticated
    USING (public.is_admin() = true);

DROP POLICY IF EXISTS "Admin delete orders" ON public.orders;
CREATE POLICY "Admin delete orders"
    ON public.orders
    FOR DELETE
    TO authenticated
    USING (public.is_admin() = true);

-- Políticas RLS para Order Items
DROP POLICY IF EXISTS "Public insert order_items" ON public.order_items;
CREATE POLICY "Public insert order_items"
    ON public.order_items
    FOR INSERT
    TO anon, authenticated
    WITH CHECK (true);

DROP POLICY IF EXISTS "Admin view order_items" ON public.order_items;
CREATE POLICY "Admin view order_items"
    ON public.order_items
    FOR SELECT
    TO authenticated
    USING (public.is_admin() = true);

DROP POLICY IF EXISTS "Admin update order_items" ON public.order_items;
CREATE POLICY "Admin update order_items"
    ON public.order_items
    FOR UPDATE
    TO authenticated
    USING (public.is_admin() = true);

-- Políticas RLS para Order Status History
DROP POLICY IF EXISTS "Admin view order_status_history" ON public.order_status_history;
CREATE POLICY "Admin view order_status_history"
    ON public.order_status_history
    FOR SELECT
    TO authenticated
    USING (public.is_admin() = true);

DROP POLICY IF EXISTS "Admin insert order_status_history" ON public.order_status_history;
CREATE POLICY "Admin insert order_status_history"
    ON public.order_status_history
    FOR INSERT
    TO authenticated
    WITH CHECK (public.is_admin() = true);
