-- ============================================================================
-- BELPA CMS — BLOQUE 2: AUTENTICACIÓN, AUTORIZACIÓN Y POLÍTICAS RLS EN SUPABASE
-- ============================================================================
-- Este script configura la autorización estricta para el panel de administración
-- asegurando que sólo los usuarios registrados en 'admin_users' con rol 'admin'
-- puedan gestionar productos o acceder a funciones administrativas.
-- ============================================================================

-- 1. TABLA DE USUARIOS ADMINISTRADORES AUTORIZADOS
CREATE TABLE IF NOT EXISTS public.admin_users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL DEFAULT 'admin' CHECK (role IN ('admin', 'editor')),
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Habilitar RLS en admin_users
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

-- Política: Un usuario autenticado solo puede leer su propio registro en admin_users
DROP POLICY IF EXISTS "Admin view own profile" ON public.admin_users;
CREATE POLICY "Admin view own profile"
    ON public.admin_users
    FOR SELECT
    TO authenticated
    USING (id = auth.uid());

-- 2. FUNCIÓN HELPER DE SEGURIDAD is_admin()
-- Utiliza SECURITY DEFINER para verificar si el usuario autenticado tiene rol 'admin' activo
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
    SELECT EXISTS (
        SELECT 1 
        FROM public.admin_users 
        WHERE id = auth.uid() 
          AND role = 'admin' 
          AND is_active = true
    );
$$;

-- 3. TABLA DE PRODUCTOS (CATÁLOGO BELPA)
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    brand TEXT NOT NULL CHECK (brand IN ('flora', 'beauty')),
    category TEXT NOT NULL,
    filter_category TEXT NOT NULL DEFAULT 'rosas_ramos',
    price TEXT NOT NULL,
    raw_price NUMERIC NOT NULL CHECK (raw_price >= 0),
    badge TEXT DEFAULT '',
    description TEXT DEFAULT '',
    media_id TEXT DEFAULT '',
    images TEXT[] NOT NULL DEFAULT '{}',
    is_active BOOLEAN NOT NULL DEFAULT true,
    is_featured BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Habilitar RLS en products
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- 4. POLÍTICAS RLS EN products
-- A) Lectura Pública: Visitantes y tienda pública solo ven productos activos
DROP POLICY IF EXISTS "Public read active products" ON public.products;
CREATE POLICY "Public read active products"
    ON public.products
    FOR SELECT
    TO anon, authenticated
    USING (is_active = true);

-- B) Lectura Administrativa: Admins verificados ven todos los productos (activos e inactivos)
DROP POLICY IF EXISTS "Admin read all products" ON public.products;
CREATE POLICY "Admin read all products"
    ON public.products
    FOR SELECT
    TO authenticated
    USING (public.is_admin() = true);

-- C) Inserción Administrativa: Solo administradores autorizados
DROP POLICY IF EXISTS "Admin insert products" ON public.products;
CREATE POLICY "Admin insert products"
    ON public.products
    FOR INSERT
    TO authenticated
    WITH CHECK (public.is_admin() = true);

-- D) Actualización Administrativa: Solo administradores autorizados
DROP POLICY IF EXISTS "Admin update products" ON public.products;
CREATE POLICY "Admin update products"
    ON public.products
    FOR UPDATE
    TO authenticated
    USING (public.is_admin() = true)
    WITH CHECK (public.is_admin() = true);

-- E) Eliminación Administrativa: Solo administradores autorizados
DROP POLICY IF EXISTS "Admin delete products" ON public.products;
CREATE POLICY "Admin delete products"
    ON public.products
    FOR DELETE
    TO authenticated
    USING (public.is_admin() = true);

-- 5. TRIGGER AUTOMÁTICO DE updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_products_updated_at ON public.products;
CREATE TRIGGER set_products_updated_at
    BEFORE UPDATE ON public.products
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- ============================================================================
-- 6. INSTRUCCIONES PARA VINCULAR EL PRIMER ADMINISTRADOR
-- ============================================================================
-- Paso 1: En la consola de Supabase (Authentication > Users), crea el usuario con su email y contraseña.
-- Paso 2: Ejecuta la siguiente consulta reemplazando el correo electrónico del administrador:
--
-- INSERT INTO public.admin_users (id, email, role, is_active)
-- SELECT id, email, 'admin', true
-- FROM auth.users
-- WHERE email = 'propietario@belpa.co'
-- ON CONFLICT (id) DO UPDATE SET role = 'admin', is_active = true;
-- ============================================================================
